### ISSUE TITLE
PSNR metric

### ISSUE THREAD

**Issue by zhangchen98** [lly-louis/INF#1]
In this code, the PSNR indicator of each patch is calculated separately, and then averaged for each image. Will the result obtained in this way be higher than that calculated directly for the entire image?

**Comment by lly-louis** [comment]
Actually, we have carefully discussed a similar question (Different Calculations of Total PSNR) in our [Supplementary Material](https://openaccess.thecvf.com/content/CVPR2023/supplemental/Li_Metadata-Based_RAW_Reconstruction_CVPR_2023_supplemental.pdf) (S4) . As to our conclusion, different calculations only result in very little PSNR difference (about 0.2~0.34 dB) compared with the total improvements.
